package edu.colostate.cs.cs414.betterbytes.p3.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.net.InetAddress;
import java.net.UnknownHostException;

import java.io.File;

import java.util.ArrayList;
import java.util.concurrent.TimeUnit;

import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

import edu.colostate.cs.cs414.betterbytes.p3.client.ClientConnection;
import edu.colostate.cs.cs414.betterbytes.p3.utilities.Tools;
import edu.colostate.cs.cs414.betterbytes.p3.wireforms.Message;
import edu.colostate.cs.cs414.betterbytes.p3.wireforms.Protocol;
import edu.colostate.cs.cs414.betterbytes.p3.wireforms.RecordsRequest;
import edu.colostate.cs.cs414.betterbytes.p3.wireforms.RecordsRequestResponse;
import edu.colostate.cs.cs414.betterbytes.p3.wireforms.UserRegistration;

/**
 *
 * @author Daniel McClure, created in NetBeans.
 */
public class UI extends javax.swing.JFrame implements ActionListener {

	private javax.swing.JButton ACCEPTBUTTON;
	private javax.swing.JList<String> CURRENTGAMESLIST;
	private javax.swing.JButton DECLINEBUTTON;
	private javax.swing.JList<String> INVITESLIST;
	private javax.swing.JButton LOGINBUTTON;
	private javax.swing.JPasswordField PASSWORD;
	private javax.swing.JButton PROFILESTATSBUTTON;
	private javax.swing.JButton QUITGAMEBUTTON;
	private javax.swing.JButton REFRESHBUTTON;
	private javax.swing.JButton RESUMEGAMEBUTTON;
	private javax.swing.JTextField USERNAME;
	private javax.swing.JButton VIEWGAMEMANUALBUTTON;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private DefaultListModel gamesListModel = new DefaultListModel();
	private DefaultListModel invitesListModel = new DefaultListModel();
	private ArrayList<String> loadedGames = new ArrayList<String>();
	private JButton SENDINVITEBUTTON = new JButton("Invite a friend...");

	
	private static ClientConnection connection; 
	
	/**
	 * Creates new form UI
	 * @throws UnsupportedLookAndFeelException 
	 * @throws IllegalAccessException 
	 * @throws InstantiationException 
	 * @throws ClassNotFoundException 
	 */
	public UI(ClientConnection connection) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
		initComponents();
		this.setTitle("Tafl Control Panel    |    Profile: ");
		this.refreshData();
		this.connection = connection;
		start();
		this.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		LOGINBUTTON = new javax.swing.JButton();
		PASSWORD = new javax.swing.JPasswordField();
		USERNAME = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		CURRENTGAMESLIST = new javax.swing.JList<>();
		jScrollPane2 = new javax.swing.JScrollPane();
		INVITESLIST = new javax.swing.JList<>();
		jLabel2 = new javax.swing.JLabel();
		REFRESHBUTTON = new javax.swing.JButton();
		ACCEPTBUTTON = new javax.swing.JButton();
		DECLINEBUTTON = new javax.swing.JButton();
		RESUMEGAMEBUTTON = new javax.swing.JButton();
		QUITGAMEBUTTON = new javax.swing.JButton();
		VIEWGAMEMANUALBUTTON = new javax.swing.JButton();
		PROFILESTATSBUTTON = new javax.swing.JButton();

		LOGINBUTTON.addActionListener(this);
		REFRESHBUTTON.addActionListener(this);
		ACCEPTBUTTON.addActionListener(this);
		DECLINEBUTTON.addActionListener(this);
		RESUMEGAMEBUTTON.addActionListener(this);
		QUITGAMEBUTTON.addActionListener(this);
		VIEWGAMEMANUALBUTTON.addActionListener(this);
		PROFILESTATSBUTTON.addActionListener(this);
		SENDINVITEBUTTON.addActionListener(this);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));
		jPanel1.setName("Login"); // NOI18N

		LOGINBUTTON.setText("Login");

		PASSWORD.setText("jPasswordField1");

		USERNAME.setText("Username");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(PASSWORD).addComponent(USERNAME).addComponent(LOGINBUTTON,
										javax.swing.GroupLayout.PREFERRED_SIZE, 111,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(USERNAME, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(LOGINBUTTON)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jLabel1.setText("Current Games:");

		jScrollPane1.setViewportView(CURRENTGAMESLIST);

		jScrollPane2.setViewportView(INVITESLIST);

		jLabel2.setText("Invites:");

		REFRESHBUTTON.setText("Refresh");

		ACCEPTBUTTON.setText("Accept");

		DECLINEBUTTON.setText("Decline");

		RESUMEGAMEBUTTON.setText("Resume");

		// QUITGAMEBUTTON.setBackground(new java.awt.Color(153, 0, 0));
		QUITGAMEBUTTON.setForeground(new java.awt.Color(255, 0, 0));
		QUITGAMEBUTTON.setText("Forfeit Game");

		VIEWGAMEMANUALBUTTON.setText("View Game Manual");

		PROFILESTATSBUTTON.setText("Profile Stats");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING, false).addGroup(layout
								.createSequentialGroup().addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
												.createSequentialGroup()
												.addComponent(RESUMEGAMEBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE,
														101, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(QUITGAMEBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addComponent(jScrollPane1))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel2).addGroup(layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addGroup(layout.createSequentialGroup()
														.addComponent(ACCEPTBUTTON,
																javax.swing.GroupLayout.PREFERRED_SIZE, 95,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(DECLINEBUTTON,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addComponent(REFRESHBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(VIEWGAMEMANUALBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(SENDINVITEBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(PROFILESTATSBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addComponent(REFRESHBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1).addComponent(jLabel2))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233,
												Short.MAX_VALUE)
										.addComponent(jScrollPane2)))
						.addGroup(layout.createSequentialGroup()
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(VIEWGAMEMANUALBUTTON)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(SENDINVITEBUTTON)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(PROFILESTATSBUTTON)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(RESUMEGAMEBUTTON).addComponent(QUITGAMEBUTTON).addComponent(ACCEPTBUTTON)
								.addComponent(DECLINEBUTTON))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	/**
	 * @param args
	 *            the command line arguments
	 * @throws UnknownHostException 
	 * @throws InterruptedException 
	 */
	public static void main(String args[]) throws UnknownHostException, InterruptedException {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		/*java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new UI().setVisible(true);
			}
		});*/
	}

	public void refreshData() {
		String absPath = System.getProperty("user.dir") + "/src/";
		this.gamesListModel.clear();
		Message reply = ClientConnection.getInstance().send(new RecordsRequest("Dan"));
		if(reply.getType().equals(Protocol.RECORDS_REQUEST_RESPONSE)) {		
			RecordsRequestResponse rr = (RecordsRequestResponse) reply;
			if(rr != null) {
				
			}
		}
		for (File f : new File(absPath + "edu/colostate/cs/cs414/betterbytes/p3/data/games").listFiles()) {
			Tools.log(f.getName());
			this.gamesListModel.addElement(f.getName());
			CURRENTGAMESLIST.setModel(gamesListModel);
			this.loadedGames.add(Tools.getFileData(f));
		}
	}

	public void login() {

	}

	public void resumeGame() {

	}

	public void forfeitGame() {

	}

	public void acceptGame() {

	}

	public void declineGame() {

	}

	public void gameManual() {
		String desc = "The game is one of pure strategy, played on a square board. A king and a small force of defenders occupy the centre of the board. A larger force of attackers, twice as numerous as the defenders, occupy positions around the edge of the board. The objective of the king is to escape to the periphery of the board, while the objective of the attackers is to capture the king, preventing his escape. The pieces move orthogonally, like rooks in chess, and capture is by surrounding a piece on two opposite sides";
		new TextUI("Game Manual", desc);
	}

	public void profileStats() {
		new TextUI("Profile Stats", this.getStats());
	}

	public String getStats() {
		return "Profile stats!";
	}

	public void sendInviteTo(String email) {

	}

	@Override
	public void actionPerformed(ActionEvent e) {
		Tools.log(e.getActionCommand());
		switch (e.getActionCommand()) {
		case "Login":
			System.out.println("USERNAME: " + USERNAME.getText() + ", PASSWORD: " + PASSWORD.getText());
			connection.send(new UserRegistration(USERNAME.getText(),PASSWORD.getText()));
			break;
		case "Refresh":
			this.refreshData();
			break;
		case "Resume":
			if (CURRENTGAMESLIST.getSelectedValue() != null) {
				// resume game
				if (CURRENTGAMESLIST.getSelectedValue() != null)
					new GameFrame(this.loadedGames.get(CURRENTGAMESLIST.getSelectedIndex()));
			}
			break;
		case "View Game Manual":
			this.gameManual();
			break;
		case "Profile Stats":
			this.profileStats();
			break;
		case "Invite a friend...":
			String email = JOptionPane.showInputDialog(this, "Enter email: ", "Invitation",
					JOptionPane.WARNING_MESSAGE);
			this.sendInviteTo(email);
			break;
		}
	}
	
	public void start() throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
		for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
			if ("Nimbus".equals(info.getName())) {
				javax.swing.UIManager.setLookAndFeel(info.getClassName());
				break;
			}
		}
		
	}

}
